name: run_api_tests

on:
  push:
    branches-ignore:
      - "**"
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [main, dev]
  repository_dispatch:
    types: [run_api_tests]
  schedule:
    - cron: "0 0 * * 0"

###############
# Set the Job #
###############
jobs:
  UnitTest:
    name: Unit Test Cases
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      - name: Install npm dependencies
        run: npm install

      - name: Create env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Run unit test cases
        run: |
          TIMESTAMP=$(date +"%Y/%m/%d/%H/%M/%S")
          LOG_FILE="unit-test-report-${TIMESTAMP}.log"
          npm run test > $LOG_FILE
          echo "Unit Test Report: $LOG_FILE"

      - name: Install Python and Azure Dependencies
        if: always()
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip -y
          pip3 install azure-storage-blob

      - name: Upload Unit Test Report to Azure Blob Storage
        if: always()
        env:
          AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
          AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
          AZURE_STORAGE_CONTAINER_NAME: ${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}
        run: |
          echo "
          from azure.storage.blob import BlobServiceClient, BlobClient, ContainerClient
          import os

          connect_str = os.getenv('AZURE_STORAGE_ACCOUNT_KEY')
          blob_service_client = BlobServiceClient(account_url=f'https://{os.getenv('AZURE_STORAGE_ACCOUNT_NAME')}.blob.core.windows.net', credential=connect_str)
          container_client = blob_service_client.get_container_client(os.getenv('AZURE_STORAGE_CONTAINER_NAME'))

          local_file_name = './unit-test-report-$TIMESTAMP.log'
          blob_client = container_client.get_blob_client(os.path.basename(local_file_name))

          with open(local_file_name, 'rb') as data:
              blob_client.upload_blob(data, overwrite=True)
          " > upload_to_blob.py
          python3 upload_to_blob.py

      - name: Scrape HTML and Generate report HTML
        run: node scrape.js

      - name: send email notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ job.status }} - API Testing Report | ${{ github.event_name == 'pull_request' && format('{0}-{1}', 'PR', github.event.pull_request.title)  || 'Triggered via Schema Changed' }}
          to: gs-tdei-coreteam@gaussiansolutions.com
          cc: sureshd@gaussiansolutions.com
          bcc: rakeshd@gaussiansolutions.com
          from: Workflow Notification
          attachments: test-report.html
          html_body: |
            <h2>API Testing Report</h2>
            <p>Workflow: <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">${{ github.workflow }}</a></p>
            <p>Repository: <a href="${{ github.server_url }}/${{ github.repository }}">${{ github.repository }}</a></p>
            ${{ github.event_name == 'pull_request' && format('<p>Pull Request: <a href="{0}">{1}</a></p>', github.event.pull_request.html_url, github.event.pull_request.title)  || '<br>' }}
