---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Code Review

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore:
      - '**'
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [main, dev]

###############
# Set the Job #
###############
jobs:
  UnitTest:
    name: Unit Test Cases
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      - name: Install npm dependencies
        run : npm install

      - name: Create env file
        run: |
            echo "${{ secrets.ENV_FILE }}" > .env

      - name: Run unit test cases
        run : npm run test

      - name: send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Tests failed for the new API Spec
          to: rakeshd@gaussiansolutions.com,gs-tdei-coreteam@gaussiansolutions.com
          from: rakeshd@gaussiansolutions.com
          body: The unit tests failed. Please check the API Spec, the generated client and make necessary changes
